<?php

/**
 * Role-Based Permission Configuration
 * 
 * Maps roles to modules they can access
 */

return [
    // roleId => [permissions]
    1 => [ // Super Admin
        'members.view', 'members.edit',
        'donations.view', 'donations.edit',
        'media.view', 'media.edit',
        'publications.view', 'publications.edit',
        'connect.view', 'connect.edit',
        'prayers.view', 'prayers.edit',
        'testimony.view', 'testimony.edit',
        'events.view', 'events.edit',
        'hymns.view', 'hymns.edit',
        'messaging.view', 'messaging.edit',
        'lists.view', 'lists.edit',
        'locations.view', 'locations.edit',
        'settings.view', 'settings.edit',
        'counseling.view', 'counseling.edit',
        'membercare.view', 'membercare.edit',
        'marketplace.view', 'marketplace.edit',
        'partnership.view', 'partnership.edit',
        'landing.view', 'landing.edit',
        'mobileadverts.view', 'mobileadverts.edit',
        'admin.users.view', 'admin.users.edit',
        'admin.roles.view', 'admin.roles.edit',
    ],
    2 => [ // Admin
        'members.view', 'members.edit',
        'donations.view', 'donations.edit',
        'media.view', 'media.edit',
        'publications.view', 'publications.edit',
        'connect.view', 'connect.edit',
        'prayers.view', 'prayers.edit',
        'testimony.view', 'testimony.edit',
        'events.view', 'events.edit',
        'hymns.view', 'hymns.edit',
        'messaging.view', 'messaging.edit',
        'lists.view', 'lists.edit',
        'locations.view', 'locations.edit',
        'settings.view', 'settings.edit',
        'counseling.view', 'counseling.edit',
        'membercare.view', 'membercare.edit',
        'marketplace.view', 'marketplace.edit',
        'partnership.view', 'partnership.edit',
        'landing.view', 'landing.edit',
        'mobileadverts.view', 'mobileadverts.edit',
    ],
    3 => [ // Editor
        'members.view',
        'donations.view',
        'media.view', 'media.edit',
        'publications.view', 'publications.edit',
        'connect.view', 'connect.edit',
        'prayers.view', 'prayers.edit',
        'testimony.view', 'testimony.edit',
        'events.view', 'events.edit',
        'hymns.view', 'hymns.edit',
        'messaging.view',
        'lists.view',
        'locations.view',
        'counseling.view',
        'membercare.view',
        'marketplace.view', 'marketplace.edit',
        'partnership.view', 'partnership.edit',
        'landing.view',
    ],
    4 => [ // Viewer
        'members.view',
        'donations.view',
        'media.view',
        'publications.view',
        'connect.view',
        'prayers.view',
        'testimony.view',
        'events.view',
        'hymns.view',
        'messaging.view',
        'lists.view',
        'locations.view',
        'counseling.view',
        'membercare.view',
        'marketplace.view',
        'partnership.view',
        'landing.view',
    ],
    5 => [ // Contributor
        'media.view', 'media.edit',
        'publications.view', 'publications.edit',
        'connect.view', 'connect.edit',
        'prayers.view', 'prayers.edit',
        'testimony.view', 'testimony.edit',
        'events.view',
        'marketplace.view', 'marketplace.edit',
    ],
];
